repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.7
    hooks:
      - id: uv-lock
      - id: uv-export
        args:
          - --quiet
          - --no-hashes
          - --frozen
          - --no-header
          - --no-annotate
          - --no-default-groups
          - --output-file=requirements.txt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Версия pre-commit-hooks
    hooks:
      - id: check-yaml  # Проверка YAML-файлов
      - id: end-of-file-fixer  # Добавление пустой строки в конец файла
      - id: trailing-whitespace  # Удаление лишних пробелов
      - id: check-added-large-files  # Проверка на большие файлы
      - id: check-json  # Проверка JSON-файлов
      - id: check-toml  # Проверка TOML-файлов
      - id: detect-private-key  # Поиск приватных ключей
      - id: name-tests-test  # Проверка имен тестов
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff
        args:
          - --fix
        # -   --unsafe-fixes
  # Проверка коммитов на соответствие Conventional Commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
  # Проверка новых зависимостей в safety. Работает только с poetry(
#  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#    rev: v1.3.3
#    hooks:
#      - id: python-safety-dependencies-check
#        files: pyproject.toml
